"""User model added few field

Revision ID: 00a53d0e98b4
Revises: 04bd035189cd
Create Date: 2022-12-20 19:04:27.467527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a53d0e98b4'
down_revision = '04bd035189cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('tinNumber', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tinNumber')
    op.drop_column('user', 'company')
    # ### end Alembic commands ###
