"""Notification modified

Revision ID: 0f0eed1651b4
Revises: acd5488e7ca6
Create Date: 2023-01-02 21:11:02.428423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0eed1651b4'
down_revision = 'acd5488e7ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('ts', sa.DateTime(), nullable=True))
    op.add_column('notification', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'user_id')
    op.drop_column('notification', 'ts')
    # ### end Alembic commands ###
