"""Added device messages

Revision ID: 25569dd020cb
Revises: 37c3702f191e
Create Date: 2022-10-09 13:25:10.073217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25569dd020cb'
down_revision = '37c3702f191e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_message_dev_id'), 'device_message', ['dev_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_message_dev_id'), table_name='device_message')
    op.drop_table('device_message')
    # ### end Alembic commands ###
