"""empty message

Revision ID: 48fc4c99205f
Revises: 0eedb9a71c5d
Create Date: 2022-11-18 18:53:29.705750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fc4c99205f'
down_revision = '0eedb9a71c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_power_source', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('alternative_power_source', sa.Column('long', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'long')
    op.drop_column('user', 'lat')
    op.drop_column('alternative_power_source', 'long')
    op.drop_column('alternative_power_source', 'lat')
    # ### end Alembic commands ###
