"""Adding geom field to user model

Revision ID: 691261404548
Revises: 66c550c9912f
Create Date: 2022-12-04 21:35:55.079405

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '691261404548'
down_revision = '66c550c9912f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_user_geom', 'user', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
    op.execute('UPDATE "user" SET geom = ST_SetSRID(ST_MakePoint(long, lat), 4326)')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_geom', table_name='user', postgresql_using='gist')
    op.drop_column('user', 'geom')
    # ### end Alembic commands ###
