"""Extended user model for Flask Login

Revision ID: 6e60cf4ff5a6
Revises: d752ff24cce2
Create Date: 2022-10-10 22:14:34.943951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e60cf4ff5a6'
down_revision = 'd752ff24cce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'created_on')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
