"""Added pinned Location model

Revision ID: 703bccc2ef6c
Revises: f5dc69ad3fc2
Create Date: 2022-11-14 22:20:13.658665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703bccc2ef6c'
down_revision = 'f5dc69ad3fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinned_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinned_location')
    # ### end Alembic commands ###
