"""empty message

Revision ID: 731433058dbc
Revises: 7b8bb70f17ad
Create Date: 2022-11-25 17:08:13.890468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731433058dbc'
down_revision = '7b8bb70f17ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_outages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_outages')
    # ### end Alembic commands ###
