"""added field to order model

Revision ID: 91b5f0dee6d2
Revises: fc890e2cd22c
Create Date: 2023-01-12 00:20:30.248930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b5f0dee6d2'
down_revision = 'fc890e2cd22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.execute('UPDATE "order" SET user_id = 1')
    op.alter_column('order', 'user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    op.drop_column('order', 'total')
    # ### end Alembic commands ###
