"""Added user fields

Revision ID: b55a767559ac
Revises: d752ff24cce2
Create Date: 2022-11-06 18:01:54.806747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55a767559ac'
down_revision = 'd752ff24cce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('accountId', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('firstname', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('phoneNo', sa.String(length=15), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'phoneNo')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'accountId')
    # ### end Alembic commands ###
