"""empty message

Revision ID: cd28d42bfef8
Revises: 
Create Date: 2022-11-06 14:49:51.606256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd28d42bfef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.String(length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_dev_id'), 'device', ['dev_id'], unique=True)
    op.create_table('device_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dev_id', sa.String(length=32), nullable=False),
    sa.Column('msg_type', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_message_dev_id'), 'device_message', ['dev_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('phoneNo', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_device_message_dev_id'), table_name='device_message')
    op.drop_table('device_message')
    op.drop_index(op.f('ix_device_dev_id'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
