"""Added device owner

Revision ID: cfa646efd7e4
Revises: 00a53d0e98b4
Create Date: 2022-12-21 02:25:09.274855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa646efd7e4'
down_revision = '00a53d0e98b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'owner_id')
    # ### end Alembic commands ###
