"""Added geom field to device, outage, alternative power source, schedule outage model

Revision ID: d5d92c2a6ddc
Revises: 691261404548
Create Date: 2022-12-04 23:34:32.860100

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd5d92c2a6ddc'
down_revision = '691261404548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_power_source', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('device', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('outage', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('schedule_outages', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE "alternative_power_source" SET geom = ST_SetSRID(ST_MakePoint(long, lat), 4326)')
    op.execute('UPDATE "device" SET geom = ST_SetSRID(ST_MakePoint(long, lat), 4326)')
    op.execute('UPDATE "outage" SET geom = ST_SetSRID(ST_MakePoint(long, lat), 4326)')
    op.execute('UPDATE "schedule_outages" SET geom = ST_SetSRID(ST_MakePoint(long, lat), 4326)')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_outages', 'geom')
    op.drop_column('outage', 'geom')
    op.drop_column('device', 'geom')
    op.drop_column('alternative_power_source', 'geom')
    # ### end Alembic commands ###
