"""technician and super admin field added

Revision ID: e23b0fc88882
Revises: 731433058dbc
Create Date: 2022-11-27 01:07:21.943903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23b0fc88882'
down_revision = '731433058dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('technician', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET technician = false')
    op.alter_column('user', 'technician', nullable=False)
    op.add_column('user', sa.Column('superadmin', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET superadmin = false')
    op.alter_column('user', 'superadmin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'superadmin')
    op.drop_column('user', 'technician')
    # ### end Alembic commands ###
