"""Outage estimated restoration time added

Revision ID: e2757e5705bd
Revises: 0f0eed1651b4
Create Date: 2023-01-02 21:16:17.415871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2757e5705bd'
down_revision = '0f0eed1651b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outage', sa.Column('est_end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outage', 'est_end_time')
    # ### end Alembic commands ###
