"""Added device message type column

Revision ID: f92a150b417f
Revises: 25569dd020cb
Create Date: 2022-10-10 18:56:37.682734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92a150b417f'
down_revision = '25569dd020cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_message', sa.Column('msg_type', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_message', 'msg_type')
    # ### end Alembic commands ###
